from __future__ import annotations

from mcp.server import Server

from resources.register_resources import register_resources
from tools.register_tools import register_tools
from version import SERVER_NAME, SERVER_VERSION


def create_mcp_server() -> Server:
    server = Server(
        SERVER_NAME,
        version=SERVER_VERSION,
        instructions="\n".join(
            [
                f"# RPGMaker Unite MCP Server v{SERVER_VERSION}",
                "",
                "RPGMaker Unite向けのAI開発支援MCPサーバー。",
                "8つのRPGMaker専用ツールでゲームデータを管理できます。",
                "",
                "## Critical Rules",
                "1. .metaファイルは絶対に編集しない（Unity自動管理）",
                "2. 変更前に operation で対象を確認",
                "3. Unity Editorで Tools > MCP Assistant を起動してから使用",
                "",
                "## Available Tools (10 tools)",
                "",
                "### Utility Tools (2)",
                "- `unity_ping`: 接続確認",
                "- `unity_compilation_await`: コンパイル完了待機",
                "",
                "### RPGMaker Database Tools (8)",
                "",
                "#### rpgmaker_database",
                "キャラクター、アイテム、アニメーションの管理",
                "- getDatabaseInfo: データベース情報取得",
                "- getCharacters / createCharacter / updateCharacter / deleteCharacter",
                "- getItems / createItem / updateItem / deleteItem",
                "- getAnimations / createAnimation / updateAnimation / deleteAnimation",
                "- getSystemSettings / updateSystemSettings",
                "- exportDatabase / importDatabase / backupDatabase / restoreDatabase",
                "",
                "#### rpgmaker_map",
                "マップとマップイベントの管理",
                "- getMaps / createMap / updateMap / deleteMap",
                "- getMapData / setMapData",
                "- getMapEvents / createMapEvent / updateMapEvent / deleteMapEvent",
                "- getTilesets / setTileset",
                "- getMapSettings / updateMapSettings",
                "- copyMap / exportMap / importMap",
                "",
                "#### rpgmaker_event",
                "コモンイベントとイベントコマンドの管理",
                "- getCommonEvents / createCommonEvent / updateCommonEvent / deleteCommonEvent",
                "- getEventCommands / createEventCommand / updateEventCommand / deleteEventCommand",
                "- getEventPages / createEventPage / updateEventPage / deleteEventPage",
                "- copyEvent / moveEvent / validateEvent",
                "",
                "#### rpgmaker_battle",
                "バトルシステムの管理",
                "- getBattleSettings / updateBattleSettings",
                "- getEnemies / createEnemy / updateEnemy / deleteEnemy",
                "- getTroops / createTroop / updateTroop / deleteTroop",
                "- getSkills / createSkill / updateSkill / deleteSkill",
                "- getBattleAnimations / updateBattleAnimation",
                "",
                "#### rpgmaker_system",
                "システム設定の管理",
                "- getSystemInfo",
                "- getGameVariables / setGameVariable",
                "- getSwitches / setSwitch",
                "- getSystemSettings / updateSystemSettings",
                "- getSaveData / createSaveData / loadSaveData / deleteSaveData",
                "",
                "#### rpgmaker_assets",
                "画像・音声アセットの管理",
                "- getImages / importImage / exportImage / deleteImage",
                "- getSounds / importSound / exportSound / deleteSound",
                "- getAssetInfo / organizeAssets / validateAssets",
                "- backupAssets / restoreAssets",
                "",
                "#### rpgmaker_gamestate",
                "ゲーム状態の管理",
                "- getGameState / setGameState",
                "- getPlayerData / updatePlayerData",
                "- getPartyData / updatePartyData",
                "- getInventory / updateInventory / addItemToInventory / removeItemFromInventory",
                "- getProgressFlags / setProgressFlag",
                "- getCurrentMap / setCurrentMap / teleportPlayer",
                "- resetGameState",
                "",
                "#### rpgmaker_audio",
                "オーディオシステムの管理",
                "- getAudioList",
                "- playBgm / stopBgm / setBgmVolume",
                "- playBgs / stopBgs / setBgsVolume",
                "- playMe / setMeVolume",
                "- playSe / setSeVolume",
                "- stopAllAudio",
                "- getAudioSettings / updateAudioSettings",
                "- importAudioFile / exportAudioFile / deleteAudioFile / getAudioInfo",
                "",
                "## Data Storage",
                "- Characters: Assets/RPGMaker/Storage/Character/JSON/",
                "- Items: Assets/RPGMaker/Storage/Item/JSON/",
                "- Animations: Assets/RPGMaker/Storage/Animation/JSON/",
                "- System: Assets/RPGMaker/Storage/System/",
                "- Maps: Assets/RPGMaker/Storage/Map/",
                "- Events: Assets/RPGMaker/Storage/Event/",
                "- Sounds: Assets/RPGMaker/Storage/Sounds/",
                "",
                "## Usage Example",
                "```python",
                "# Get all characters",
                "rpgmaker_database(operation='getCharacters')",
                "",
                "# Create a new character",
                "rpgmaker_database(",
                "    operation='createCharacter',",
                "    filename='hero_001',",
                "    characterData={",
                "        'name': 'Hero',",
                "        'class': 'Warrior',",
                "        'level': 1,",
                "        'stats': {'hp': 100, 'mp': 50, 'attack': 15, 'defense': 10}",
                "    }",
                ")",
                "",
                "# Get all maps",
                "rpgmaker_map(operation='getMaps')",
                "",
                "# Play background music",
                "rpgmaker_audio(operation='playBgm', filename='battle_theme', volume=0.8)",
                "```",
                "",
                "## Troubleshooting",
                "- Connection failed: Unity Editor で Tools > MCP Assistant を起動",
                "- Bridge timeout: Unity Console でエラーログを確認",
                "- Data not found: Storage パスにデータが存在するか確認",
                "",
                "---",
                f"RPGMaker Unite MCP Server v{SERVER_VERSION} - 10 Tools for RPGMaker Unite Development",
            ]
        ),
    )

    register_resources(server)
    register_tools(server)

    return server
