from __future__ import annotations

from mcp.server import Server

from resources.register_resources import register_resources
from tools.register_tools import register_tools
from version import SERVER_NAME, SERVER_VERSION


def create_mcp_server() -> Server:
    server = Server(
        SERVER_NAME,
        version=SERVER_VERSION,
        instructions="\n".join(
            [
                f"# RPGMaker Unite MCP Server v{SERVER_VERSION}",
                "",
                "RPGMaker Unite向けのAI開発支援MCPサーバー。",
                "10個のツール（ユーティリティ2個 + RPGMaker専用8個）でゲームデータを管理できます。",
                "",
                "## 重要なルール",
                "1. `.meta`ファイルは絶対に編集しない（Unity自動管理）",
                "2. 変更前に`list*`または`get*ById`でデータを確認する",
                "3. Unity Editorで `Tools > MCP Assistant` を起動してから使用",
                "",
                "## 操作パターン（UUID中心設計）",
                "",
                "全ての操作はUUIDを中心に設計されています：",
                "",
                "| パターン | 説明 | 必須パラメータ |",
                "|----------|------|---------------|",
                "| `list*` | UUID・名前の軽量リスト取得 | - |",
                "| `get*ById` | 特定UUIDの完全データ取得 | uuId |",
                "| `get*` (複数形) | ⚠️ 非推奨: 全件取得（大量データでリスク） | - |",
                "| `create*` | 新規作成（uuIdは自動生成） | data |",
                "| `update*` | 既存データ更新 | uuId, data |",
                "| `delete*` | データ削除 | uuId |",
                "",
                "### UUID自動生成",
                "- `create*`操作時、`data`内に`uuId`がなければサーバーが自動生成",
                "- `filename`はオプション（省略時はデフォルト値を使用）",
                "",
                "### 推奨ワークフロー",
                "1. `list*` でUUID一覧を取得",
                "2. `get*ById` で必要なデータの詳細を取得",
                "3. `update*` または `delete*` でUUIDを指定して操作",
                "",
                "## 利用可能なツール（10個）",
                "",
                "### ユーティリティツール（2個）",
                "- `unity_ping`: Unity Bridgeへの接続確認",
                "- `unity_compilation_await`: C#スクリプトのコンパイル完了を待機",
                "",
                "### RPGMakerツール（8個）",
                "",
                "#### rpgmaker_database",
                "キャラクター、アイテム、アニメーション、システム設定の管理",
                "",
                "| 操作 | 必須パラメータ | 説明 |",
                "|------|---------------|------|",
                "| getDatabaseInfo | - | データベース全体の情報取得 |",
                "| listCharacters | - | キャラクターUUID一覧（軽量） |",
                "| getCharacterById | uuId | 特定キャラクターの完全データ |",
                "| getCharacters | - | ⚠️ 非推奨: 全キャラクター取得 |",
                "| createCharacter | characterData | 新規作成（uuId自動生成、filename省略可） |",
                "| updateCharacter | uuId, characterData | キャラクター更新 |",
                "| deleteCharacter | uuId | キャラクター削除 |",
                "| listItems / getItemById / createItem / updateItem / deleteItem | 同パターン | アイテム管理 |",
                "| listAnimations / getAnimationById / createAnimation / updateAnimation / deleteAnimation | 同パターン | アニメーション管理 |",
                "| getSystemSettings / updateSystemSettings | settingData | システム設定 |",
                "| exportDatabase / importDatabase / backupDatabase / restoreDatabase | 各種パス（オプション） | データベース操作 |",
                "",
                "#### rpgmaker_map",
                "マップ、マップイベント、タイルセットの管理",
                "",
                "| 操作 | 必須パラメータ | 説明 |",
                "|------|---------------|------|",
                "| listMaps | - | マップUUID一覧（軽量） |",
                "| getMapById | uuId | 特定マップの完全データ |",
                "| getMaps | - | ⚠️ 非推奨: 全マップ取得 |",
                "| createMap | mapData | 新規作成（id自動生成、filename省略可） |",
                "| updateMap / deleteMap | uuId | マップ更新・削除 |",
                "| listMapEvents / getMapEventById | uuId | マップイベント取得 |",
                "| createMapEvent / updateMapEvent / deleteMapEvent | uuId, eventData | マップイベント管理 |",
                "| listTilesets / getTilesetById / setTileset | - | タイルセット管理 |",
                "| copyMap | sourceFilename, targetFilename | マップコピー |",
                "",
                "#### rpgmaker_event",
                "コモンイベント、イベントコマンド、イベントページの管理",
                "",
                "| 操作 | 必須パラメータ | 説明 |",
                "|------|---------------|------|",
                "| listCommonEvents | - | コモンイベントUUID一覧（軽量） |",
                "| getCommonEventById | uuId | 特定イベントの完全データ |",
                "| getCommonEvents | - | ⚠️ 非推奨: 全イベント取得 |",
                "| createCommonEvent | eventData | 新規作成（id自動生成、filename省略可） |",
                "| updateCommonEvent / deleteCommonEvent | uuId | イベント更新・削除 |",
                "| getEventCommands / createEventCommand / updateEventCommand / deleteEventCommand | uuId, commandIndex | イベントコマンド管理 |",
                "| getEventPages / createEventPage / updateEventPage / deleteEventPage | uuId, pageIndex | イベントページ管理 |",
                "| copyEvent / moveEvent | sourceFilename, targetFilename | イベントコピー・移動 |",
                "| validateEvent | uuId | イベント検証 |",
                "",
                "#### rpgmaker_battle",
                "敵、敵グループ、スキル、バトルアニメーションの管理",
                "",
                "| 操作 | 必須パラメータ | 説明 |",
                "|------|---------------|------|",
                "| getBattleSettings / updateBattleSettings | settingData | バトル設定 |",
                "| listEnemies / getEnemyById | - / uuId | 敵UUID一覧・詳細取得 |",
                "| getEnemies | - | ⚠️ 非推奨: 全敵取得 |",
                "| createEnemy | enemyData | 新規作成（uuId自動生成、filename省略可） |",
                "| updateEnemy / deleteEnemy | uuId | 敵更新・削除 |",
                "| listTroops / getTroopById / createTroop / updateTroop / deleteTroop | 同パターン | 敵グループ管理 |",
                "| listSkills / getSkillById / createSkill / updateSkill / deleteSkill | 同パターン | スキル管理 |",
                "| getBattleAnimations / updateBattleAnimation | - | バトルアニメーション管理 |",
                "",
                "#### rpgmaker_system",
                "ゲーム変数、スイッチ、システム設定、セーブデータの管理",
                "",
                "| 操作 | 必須パラメータ | 説明 |",
                "|------|---------------|------|",
                "| getSystemInfo | - | システム情報取得 |",
                "| getGameVariables / setGameVariable | variableId, value | ゲーム変数管理 |",
                "| getSwitches / setSwitch | switchId, value | スイッチ管理 |",
                "| getSystemSettings / updateSystemSettings | systemSettings | システム設定 |",
                "| getSaveData / createSaveData / loadSaveData / deleteSaveData | slotId | セーブデータ管理 |",
                "",
                "#### rpgmaker_assets",
                "画像・音声アセットの管理",
                "",
                "| 操作 | 必須パラメータ | 説明 |",
                "|------|---------------|------|",
                "| listImages / getImageById | category | 画像ファイル一覧・詳細取得 |",
                "| getImages | category | ⚠️ 非推奨: 全画像取得 |",
                "| importImage / exportImage / deleteImage | category, filename | 画像管理 |",
                "| listSounds / getSoundById | category | 音声ファイル一覧・詳細取得 |",
                "| getSounds | category | ⚠️ 非推奨: 全音声取得 |",
                "| importSound / exportSound / deleteSound | category, filename | 音声管理 |",
                "| getAssetInfo / organizeAssets / validateAssets | - | アセット情報・整理・検証 |",
                "| backupAssets / restoreAssets | backupPath（オプション） | アセットバックアップ |",
                "",
                "#### rpgmaker_gamestate",
                "プレイヤー、パーティ、インベントリ、進行フラグの管理",
                "",
                "| 操作 | 必須パラメータ | 説明 |",
                "|------|---------------|------|",
                "| getGameState / setGameState | gameStateData | ゲーム状態管理 |",
                "| getPlayerData / updatePlayerData | playerData | プレイヤーデータ |",
                "| getPartyData / updatePartyData | partyData | パーティデータ |",
                "| getInventory / updateInventory | inventoryData | インベントリ管理 |",
                "| addItemToInventory / removeItemFromInventory | itemId, quantity | アイテム追加・削除 |",
                "| getProgressFlags / setProgressFlag | flagType, flagId, value | 進行フラグ管理 |",
                "| getCurrentMap / setCurrentMap | mapId | 現在マップ管理 |",
                "| teleportPlayer | mapId, x, y, direction | プレイヤーテレポート |",
                "| resetGameState | - | ゲーム状態リセット |",
                "",
                "#### rpgmaker_audio",
                "BGM・BGS・ME・SEの再生・停止・音量管理",
                "",
                "| 操作 | 必須パラメータ | 説明 |",
                "|------|---------------|------|",
                "| listAudioFiles / getAudioFileById | category | オーディオファイル一覧・詳細取得 |",
                "| getAudioList | category | ⚠️ 非推奨: 全オーディオ取得 |",
                "| playBgm / playBgs / playMe / playSe | filename | オーディオ再生（volume省略可） |",
                "| stopBgm / stopBgs / stopAllAudio | - | オーディオ停止 |",
                "| setBgmVolume / setBgsVolume / setMeVolume / setSeVolume | volume | 音量設定（0.0-1.0） |",
                "| getAudioSettings / updateAudioSettings | settingsData | オーディオ設定 |",
                "| importAudioFile / exportAudioFile / deleteAudioFile | category, filename | オーディオファイル管理 |",
                "| getAudioInfo | filename | オーディオ情報取得 |",
                "",
                "## データ保存場所",
                "| データ種別 | パス |",
                "|-----------|------|",
                "| キャラクター | Assets/RPGMaker/Storage/Character/JSON/ |",
                "| アイテム | Assets/RPGMaker/Storage/Item/JSON/ |",
                "| アニメーション | Assets/RPGMaker/Storage/Animation/JSON/ |",
                "| システム | Assets/RPGMaker/Storage/System/ |",
                "| マップ | Assets/RPGMaker/Storage/Map/ |",
                "| イベント | Assets/RPGMaker/Storage/Event/ |",
                "| サウンド | Assets/RPGMaker/Storage/Sounds/ |",
                "",
                "## ペジネーション",
                "一覧取得系の操作では`offset`と`limit`パラメータでページングが可能です：",
                "- `offset`: スキップする件数（デフォルト: 0）",
                "- `limit`: 取得する最大件数（デフォルト: 100、-1で無制限）",
                "",
                "## 使用例",
                "",
                "```python",
                "# 1. UUID一覧を軽量に取得（推奨）",
                "rpgmaker_database(operation='listCharacters')",
                "# → [{uuId: 'abc-123', name: 'クラフト', filename: 'characterActor'}, ...]",
                "",
                "# 2. 特定UUIDの詳細を取得",
                "rpgmaker_database(operation='getCharacterById', uuId='abc-123-def')",
                "",
                "# 3. 新規作成（uuId自動生成、filenameはオプション）",
                "rpgmaker_database(",
                "    operation='createCharacter',",
                "    characterData={",
                "        'basic': {'name': '勇者'},",
                "        'charaType': 1,",
                "        'initialLevel': 1",
                "    }",
                ")",
                "# → {uuId: '新規生成されたUUID', filename: 'characterActor'}",
                "",
                "# 4. UUIDを指定して更新",
                "rpgmaker_database(",
                "    operation='updateCharacter',",
                "    uuId='abc-123-def',",
                "    characterData={'basic': {'name': '勇者改'}},",
                "    partial=True  # 部分更新",
                ")",
                "",
                "# 5. UUIDを指定して削除",
                "rpgmaker_database(operation='deleteCharacter', uuId='abc-123-def')",
                "",
                "# マップ一覧取得（ページネーション）",
                "rpgmaker_map(operation='listMaps', offset=0, limit=10)",
                "",
                "# BGM再生（volumeはオプション、デフォルト0.8）",
                "rpgmaker_audio(operation='playBgm', filename='battle_theme')",
                "```",
                "",
                "## トラブルシューティング",
                "| 問題 | 解決方法 |",
                "|------|---------|",
                "| 接続失敗 | Unity Editorで `Tools > MCP Assistant` を起動 |",
                "| タイムアウト | Unity Consoleでエラーログを確認 |",
                "| データ未検出 | Storageパスにデータが存在するか確認 |",
                "| 更新失敗 | `uuId`が正しいか`listXxx`で確認 |",
                "",
                "---",
                f"RPGMaker Unite MCP Server v{SERVER_VERSION} - RPGMaker Unite開発用10ツール",
            ]
        ),
    )

    register_resources(server)
    register_tools(server)

    return server
